### ISSUE TITLE
No keyboard delete on Mac

### ISSUE THREAD

**Issue by prikhi** [prikhi/pencil#191]
_From [101webt...@gmail.com](https://code.google.com/u/105835292960696215461/) on July 12, 2010 07:29:09_

What steps will reproduce the problem? 1. Use a shape by dragging to canvas area.
2. Select the shape and press the [delete] key.

What is the expected output? 
I expected for the shape to be deleted from the canvas

What do you see instead?
The shape was not deleted from the canvas What version of the product are you using? On what operating system? Firefox Addon - Version 1.2
Snow Leopard 10.6.4 Please provide any additional information below.

_Original issue: http://code.google.com/p/evoluspencil/issues/detail?id=191_

**Comment by prikhi** [comment]
_From [dejong.a...@gmail.com](https://code.google.com/u/108233280219621621069/) on July 17, 2010 01:49:23_

Delete on a Mac is more like Backspace on a PC.
(at last on my Macbook Pro, it might be configurable)

Possible workaround: use FN + Delete to delete a shape.

**Comment by prikhi** [comment]
_From [jcscoob...@gmail.com](https://code.google.com/u/103960149060463949301/) on September 24, 2010 21:25:23_

I concur...this should be closed as not a bug.

**Comment by prikhi** [comment]
_From [dejong.a...@gmail.com](https://code.google.com/u/108233280219621621069/) on September 28, 2010 09:46:27_

I wouldn't say close this bug.
Comparable applications allow both Delete and Backspace for deleting shapes.
The workaround is there, but it would be nice to not have to use the workaround.

**Comment by prikhi** [comment]
_From [lukas.ry...@gmail.com](https://code.google.com/u/106011028162100206992/) on May 12, 2012 06:31:29_

Hi, I've create a fork of Pencil and I've added backspace as shortcut for deleting shapes. You can download build from Github https://github.com/LukasRychtecky/pencil

**Comment by prikhi** [comment]
_From [Julian.K...@gmail.com](https://code.google.com/u/112562222511949775125/) on November 13, 2012 07:39:39_

fn+delete doesn't work either. This, and several other shortcuts, are must haves, in my book. I added an issue for the others here: https://code.google.com/p/evoluspencil/issues/detail?id=511&thanks=511&ts=1352821148

**Comment by rschiang** [comment]
@prikhi Any chance to merge the change into master branch? Or how could we help? :)

**Comment by prikhi** [comment]
Didn't know a fix existed(all comments are from google code import).

I'll get this in soon, the fix is simple: https://github.com/LukasRychtecky/pencil/commit/52dbc37c3bb371dd172b4f40645d9978959d85b4

**Comment by rschiang** [comment]
:+1:

**Comment by prikhi** [comment]
I'm on the road so I don't have the ability to make a new release, should be back home around nov 10th or so

**Comment by rschiang** [comment]
Have a nice trip!
