### ISSUE TITLE
Can't drag and drop images into working area

### ISSUE THREAD

**Issue by prikhi** [prikhi/pencil#316]
_From [francesc...@gmail.com](https://code.google.com/u/108060081327411251145/) on June 21, 2011 17:18:18_

What steps will reproduce the problem? 1. Drag & drop any image into Pencil 1.2
2. The image won't be added to the working area, a "can't do" kind of cursor appears. What is the expected output? What do you see instead? I'd like to get the image I dragged into the working area. But I see nothing. What version of the product are you using? On what operating system? Pencil 1.2 on Windows Seven x64. I even tried XP SP3 compatibility mode. Please provide any additional information below. I've been working today on a Windows XP computer with the same Pencil version, and got no problems. Maybe this is just a bad behaviour in W7.

_Original issue: http://code.google.com/p/evoluspencil/issues/detail?id=316_

**Comment by prikhi** [comment]
_From [ameer...@gyrusretail.com](https://code.google.com/u/114152632543334090768/) on February 04, 2012 08:26:48_

same issue with me too... the tool is fantastic but this is totally frustrating... 

the PC I started working on was fine, but when i came back home and installed pencil on my PC am not able to drag drop images, and also the saved *.ep dint carry my collection and also the images i used in making my Doc... totally frustrating as i have done soo much work ... totally wasted my time ...

GUYS this is the best tool i like on the first go but am totally disappointed due to this issue which caused me to start all over again, resolve this asap

**Comment by prikhi** [comment]
_From [ameer...@gyrusretail.com](https://code.google.com/u/114152632543334090768/) on February 04, 2012 22:28:49_

Observation :

The PC on which everything runs fine is not asking me for administrative rights every time am launching Pencil tool... and today i open the previously work file on this system and all the images are missing.

**Comment by prikhi** [comment]
_From [projektas](https://code.google.com/u/projektas/) on April 11, 2012 06:49:06_

Me to. Please FIX that.

**Comment by prikhi** [comment]
_From [s1thre...@gmail.com](https://code.google.com/u/100037932796160069819/) on April 11, 2012 06:52:14_

Best solution, get Firefox n install Pencil tool as add-on... Works like a charm

**Comment by prikhi** [comment]
_From [d.phanin...@gmail.com](https://code.google.com/u/100259883471931677869/) on March 06, 2015 02:20:22_

Try it in firefox add on and then try in desktop version, it works perfectly.

**Comment by belinifm** [comment]
I have the same issue, drag and drop not work in Pencil 2.0.5
My system:
- AMD A10-5800B APU Radeon HD7660D
- RAM 16 GB 
- Debian GNU/Linux 8 (jessie) 64-bit

**Comment by prikhi** [comment]
see #856

**Comment by prikhi** [comment]
Also, v2.0.5 is evolus' version, first release of this repo was v2.0.6
