### ISSUE TITLE
wrong behavior of the export templates

### ISSUE THREAD

**Issue by prikhi** [prikhi/pencil#358]
_From [peter.u...@gmail.com](https://code.google.com/u/107886393993805019253/) on November 02, 2011 06:54:57_

What steps will reproduce the problem? 1.  export multipage document via lefttab, jquery, tab navigation or default html template
2. first screen is empty or the last one is there instead (the last one is then repeated in its propoer position 3. What is the expected output? What do you see instead? first page in html export displaying the first page from the app What version of the product are you using? On what operating system? FF 7.0.1
macos 10.7.2
pencil 1.3.2 (this behavior was in older versions too), no idea if the problem is the tempplate or the app, but on windows it works ok Please provide any additional information below.

_Original issue: http://code.google.com/p/evoluspencil/issues/detail?id=358_

**Comment by prikhi** [comment]
_From [john.ro...@gmail.com](https://code.google.com/u/108283553742324961944/) on April 04, 2014 13:22:34_

I think I am having a very similar problem.  When I export to the Tab template, some pages are repeated.. so when I export Page1, Page2, Page3, Page 4

I get:
Page1 (contents of page1)
Page2 (contents of page2)
Page3 (contents of Page3) **
Page4 (contents of page4)

So far I cannot figure out what is causing this problem.

Thanks

**Comment by punknroll** [comment]
I have the same issue. 
Steps to reproduce:
- open a new file and create page1, page2, and page3
- save the file and close the application
- reopen the application and reopen the file
- Document, Export Document, Single web page, All pages in the document

The background of page2 is the same as page1. When you select page2 then page3 has the same background as page2. So it seems that the next page after the selected page gets the wrong background image. If you select the last page then all backgrounds are right.

greetz Andy

**Comment by prikhi** [comment]
Thanks, there's so many old issues - I appreciate the confirmation that this still exists.

**Comment by prikhi** [comment]
Looks like this is caused by #602. After reopening, exporting is fixed if you click each individual tab first.

**Comment by prikhi** [comment]
I was wrong, it's unrelated to #602 - but incidentally I found a fix while I was trying to solve #602.
