### ISSUE TITLE
Select all + delete results in serious data loss

### ISSUE THREAD

**Issue by prikhi** [prikhi/pencil#406]
_From [uin....@googlemail.com](https://code.google.com/u/104765925504650252116/) on January 30, 2012 10:28:12_

What steps will reproduce the problem? 1. Open Pencil and create a new document.
2. Drop a few elements/shapes on the first page.
3. Create a new (second) page.
4. Drop a few elements/shapes on the second page.
5. Press ctrl+a to select every shape/element on the second page.
6. Press the delete button on your keyboard.
7. The selected shapes + most of the shapes on all the other pages are deleted. What is the expected output? What do you see instead? I exptected that only the shapes on the current page were deleted and not all of them. What version of the product are you using? On what operating system? 1.3.4 (Windows XP) Please provide any additional information below.

_Original issue: http://code.google.com/p/evoluspencil/issues/detail?id=406_

**Comment by jdittrich** [comment]
Could **not** reproduce this using Pencil 2.10 on Firefox 38 on Ubuntu 14.04.2

**Comment by prikhi** [comment]
Thanks
