### ISSUE TITLE
Move repo to git to simplify contributing

### ISSUE THREAD

**Issue by prikhi** [prikhi/pencil#426]
_From [anatoly....@gmail.com](https://code.google.com/u/115846696075841189927/) on March 14, 2012 20:41:21_

It's much easier to contribute there.

_Original issue: http://code.google.com/p/evoluspencil/issues/detail?id=426_

**Comment by mvdw** [comment]
This is now irrelevant/done.

**Comment by prikhi** [comment]
Thanks :)
