### ISSUE TITLE
Spelling Error on Top Level of UI

### ISSUE THREAD

**Issue by prikhi** [prikhi/pencil#430]
_From [cbrady...@gmail.com](https://code.google.com/u/115917747470377515176/) on March 28, 2012 07:00:34_

What steps will reproduce the problem? > expose "My Stuffs" tab in version 1.3.4

It's a common mistake in English, abstract quantities are automatically plural.  Stuff happens to be an abstract quantity so "My Stuffs" should be "My Stuff".

Great project!

_Original issue: http://code.google.com/p/evoluspencil/issues/detail?id=430_

**Comment by mvdw** [comment]
This is fixed in V2.0.11 or before.

**Comment by prikhi** [comment]
Thanks :)
