### ISSUE TITLE
gdaga

### ISSUE THREAD

**Issue by prikhi** [prikhi/pencil#441]
_From [fantunes...@gmail.com](https://code.google.com/u/116337104241000032731/) on May 01, 2012 11:38:38_

What steps will reproduce the problem? 1. 2. 3. What is the expected output? What do you see instead? What version of the product are you using? On what operating system? Please provide any additional information below.

_Original issue: http://code.google.com/p/evoluspencil/issues/detail?id=441_

**Comment by mvdw** [comment]
This is not a bug. Please close this.
Also the original is empty.

**Comment by prikhi** [comment]
haha, thanks again :)
