### ISSUE TITLE
Sometimes drag and drop fails

### ISSUE THREAD

**Issue by prikhi** [prikhi/pencil#467]
_From [julien.b...@gmail.com](https://code.google.com/u/114824020001156408010/) on July 25, 2012 06:06:52_

First of all, it doesn't happen necessarily every time as I have issues reproducing it, but it is definitely there. What steps will reproduce the problem? 1. Add a gradient rectangle to the canvas which covers the TOP as in :
   gradientRectangle.Width = canvas.Width
   gradientRectangle.Height = A few hundred pixels
2. Add a Box to the canvas which covers the LEFT of the canvas as in :
   box.Width = A few hundred pixels
   box.Height = canvas.Height
3. Add a table to the canvas at the bottom right, doesn't matter where
4. Add a link to the canvas at the bottom right, anywhere What is the expected output? What do you see instead? I expect all the items to be drag and dropped where I put them. Instead it seems the table is dropped I cannot add anything any more. The only thing to do is to restart to app to keep going. What version of the product are you using? On what operating system? v1.3.4 Please provide any additional information below. I'm running the standalone version on win7/x64

Julien

_Original issue: http://code.google.com/p/evoluspencil/issues/detail?id=467_

**Comment by prikhi** [comment]
_From [james.g....@gmail.com](https://code.google.com/u/106277629041379334470/) on September 14, 2012 16:38:54_

I have this problem under Windows 7 64-bit standalone and under Ubuntu 12.04 running via Firefox (15.0.1). Problem appears to be specific to what is being dragged. Some objects refuse to drag at all. Some will work on a new page but then fail as soon as something else is added. There doesn't appear to be any clear reason why.

Steps to reproduce running within firefox on Ubuntu 12.04.  
1. Create new page.
2. Drag Rectangle on to page.
3. Drag oval onto page.

Step 3 fails. It cannot be dragged onto the page. Attempting to add a new rectangle also fails until a new page is open.

Effectively the problem makes Pencil unusable both under Windows 7 (64-bit) as standalone and within Firefox under Ubutnu 12.04. 

I would suggest that the priority is increased from medium to a higher level as currently the tool is unusable in the environments I have tested.

**Comment by prikhi** [comment]
_From [james.g....@gmail.com](https://code.google.com/u/106277629041379334470/) on September 14, 2012 16:46:44_

While doing further testing have determined that under the Ubuntu 12.04/Firefox environment that the drag failure is related to the speed of the drag operation. 

If the drag is slow enough then the drag to add a shape to the page works 100% of the time.

If the drag action is above a certain speed then the drag fails.

This appears to be the reason why it's hard to recreate as speed of the drag operation is what affects the failure of the page to become a target. It appears that what happens is the page is made a target of the drag operation briefly, but then the page is removed as a drag target, thus stopping the drag operation to work. 

The work around is to drag slowly. It is possible that this is a problem for people who have enabled fast acceleration of their mouse (which I have, on both environments). The reason for enabling fast acceleration is because on environment makes use of a 30 inch monitor and the other uses two large monitors.

**Comment by Mafioziks** [comment]
For me drag & drop does not work at all. I am using Lubuntu 16.04.

**Comment by Roshanarr** [comment]
drag and drop doesnot work in pencil tool for ubuntu

**Comment by prikhi** [comment]
See #802, #856
