### ISSUE TITLE
Twitter Bootstrap stencil

### ISSUE THREAD

**Issue by prikhi** [prikhi/pencil#490]
_From [projektas](https://code.google.com/u/projektas/) on October 01, 2012 06:55:13_

Please make bootstrap stencil http://twitter.github.com/bootstrap/ This is popular CSS framework around web designers and developers.

_Original issue: http://code.google.com/p/evoluspencil/issues/detail?id=490_

**Comment by prikhi** [comment]
_From [mpanc...@gmail.com](https://code.google.com/u/112728932909188619052/) on February 25, 2013 08:18:18_

I second that.. it would be pretty useful to have a Twitter Bootstrap stencil for Evolus Pencil ( a very useful free tool I have to say!)

**Comment by prikhi** [comment]
_From [martin.blaha](https://code.google.com/u/martin.blaha/) on March 16, 2013 11:33:14_

Yes please!! That'd be so great!

**Comment by prikhi** [comment]
_From [layto...@gmail.com](https://code.google.com/u/117771396732275236949/) on May 28, 2013 17:10:24_

agreed!

**Comment by prikhi** [comment]
_From [jewelsja...@gmail.com](https://code.google.com/u/112295264892734855900/) on June 26, 2013 14:51:40_

Then I don't have to pay $30 month for Protoshare!

**Comment by prikhi** [comment]
_From [coolpa...@gmail.com](https://code.google.com/u/105385584185424810754/) on July 06, 2013 05:09:11_

Yes a must have ! +1000

**Comment by prikhi** [comment]
_From [ed.co...@gmail.com](https://code.google.com/u/110106601260984294607/) on July 24, 2013 07:44:37_

Debe tenerlo, sino Pencil queda en una posición muy  débil para prototipos web frente a otras herramientas.

It must have it, otherwise Pencil is in a very weak position compared to other web prototyping tools.

**Comment by prikhi** [comment]
_From [dhamas...@gmail.com](https://code.google.com/u/103163019522208134187/) on July 24, 2013 20:31:46_

Yeah, i need this too

**Comment by prikhi** [comment]
_From [radu.luc...@gmail.com](https://code.google.com/u/101194768754753001594/) on July 29, 2013 00:33:58_

It would be great to have this stencil!

**Comment by prikhi** [comment]
_From [slopezga...@gmail.com](https://code.google.com/u/106500280620545186246/) on August 07, 2013 10:48:44_

1+

**Comment by prikhi** [comment]
_From [alejandr...@tuned.com.ar](https://code.google.com/u/107218456925800291771/) on August 08, 2013 07:09:23_

1+

**Comment by prikhi** [comment]
_From [aamironl...@gmail.com](https://code.google.com/u/112019176813214045004/) on August 09, 2013 22:52:18_

From me too...

**Comment by prikhi** [comment]
_From [jozeman...@gmail.com](https://code.google.com/u/103732087215304048437/) on August 25, 2013 19:45:15_

1+ agree

**Comment by prikhi** [comment]
_From [vivek.pa...@indiatimes.co.in](https://code.google.com/u/115016694660676092356/) on August 30, 2013 01:32:54_

I agree

**Comment by prikhi** [comment]
_From [wce...@gmail.com](https://code.google.com/u/117385390239717414588/) on September 03, 2013 08:20:05_

Agree

**Comment by prikhi** [comment]
_From [mjncic...@gmail.com](https://code.google.com/u/112594848654258340936/) on September 09, 2013 20:04:24_

Agree!

**Comment by prikhi** [comment]
_From [piee...@gmail.com](https://code.google.com/u/101940230705842842939/) on October 02, 2013 07:16:25_

1+ agree

**Comment by prikhi** [comment]
_From [mattbrac...@eclipse-tech.co.uk](https://code.google.com/u/113308538400272040796/) on October 02, 2013 08:42:19_

1+ agree

**Comment by prikhi** [comment]
_From [arces...@gmail.com](https://code.google.com/u/110631692137799828431/) on October 02, 2013 10:27:47_

1+ year

**Comment by prikhi** [comment]
_From [riadhjou...@gmail.com](https://code.google.com/u/117604406856239121550/) on October 28, 2013 08:29:31_

would be great

**Comment by prikhi** [comment]
_From [bhanu.b...@gmail.com](https://code.google.com/u/108698048039425789732/) on October 28, 2013 21:22:00_

In this time, Pencil project + BootStrap(responsive) = complete prototyping solution for web.

**Comment by prikhi** [comment]
_From [sven.sch...@gmail.com](https://code.google.com/u/114314689928710703888/) on November 17, 2013 04:57:57_

Yes, 1+ - would be awesome.

**Comment by prikhi** [comment]
_From [Adriano....@gmail.com](https://code.google.com/u/115166333981694982146/) on November 24, 2013 15:13:29_
- 10'000 :-) Thanks!

**Comment by prikhi** [comment]
_From [killua...@gmail.com](https://code.google.com/u/101221412781007314227/) on January 02, 2014 19:53:48_

I Agree too :)

**Comment by prikhi** [comment]
_From [tunec...@gmail.com](https://code.google.com/u/114319965730764736647/) on January 15, 2014 12:10:07_

1+

**Comment by prikhi** [comment]
_From [ungar...@gmail.com](https://code.google.com/u/107273292237278531739/) on January 17, 2014 14:42:20_

1+

**Comment by prikhi** [comment]
_From [pjryan...@gmail.com](https://code.google.com/u/109261783767921976836/) on January 18, 2014 09:24:29_

1+

**Comment by prikhi** [comment]
_From [francesc...@gmail.com](https://code.google.com/u/108060081327411251145/) on February 05, 2014 02:16:19_

Please. +1

**Comment by prikhi** [comment]
_From [enterthe...@gmail.com](https://code.google.com/u/109399338648242537995/) on February 16, 2014 17:19:27_

http://bootstrapuikit.com/ for help us)

**Comment by prikhi** [comment]
_From [beto.cor...@gmail.com](https://code.google.com/u/116085050201286738024/) on February 19, 2014 09:39:17_

Hello I created a very similar to bootstrap collection. It is hardly a stencil, but found very practical and can be tailored according to the needs.

To download click on the tab "My Stuff" and then click the right button and go to the "Import new private collection" option.

Still recommend you install the stencil "Font Awesome Icons".

**Attachment:** [Bootstrap.zip](http://code.google.com/p/evoluspencil/issues/detail?id=490#hc31)

**Comment by prikhi** [comment]
_From [vytenis....@gmail.com](https://code.google.com/u/101689473599124728419/) on February 24, 2014 04:46:49_

Thank you so much for this "Stuff"

**Comment by prikhi** [comment]
_From [b...@ciklum.com](https://code.google.com/u/114855798049754876856/) on March 24, 2014 04:20:19_

Hi,
I found that Font Awesome actually provide a good solution for using icon in any desktop based program such as Pencil, Word, Adobe suit. It's not as easy as using Stencils in Pencil, but it's close.

Install
1) Download the latest zip-file form the Font Awesome page ( http://fontawesome.io/ )
2) Extract the zip-file and install FontAwesome.otf font on your computer
3) Save the Cheatsheet page as PDF ( http://fontawesome.io/cheatsheet/ )

Use in Pencil
1) Open Pencil and create a new text area (Simple or Rich)
2) Choose Font Awesome as font
3) Copy and past a icon from the Cheatsheet PDF (Not icon class or unicode)

Sit back and enjoy :-)

**Comment by prikhi** [comment]
_From [Rek...@gmail.com](https://code.google.com/u/114184624410070216014/) on July 31, 2014 06:14:18_

1+

**Comment by prikhi** [comment]
_From [gold...@gmail.com](https://code.google.com/u/111093951545510503272/) on July 31, 2014 06:29:38_

1++

**Comment by prikhi** [comment]
_From [rudi.ver...@gmail.com](https://code.google.com/u/116643133411308687097/) on August 25, 2014 02:04:38_

1+

**Comment by prikhi** [comment]
_From [gustavo....@gmail.com](https://code.google.com/u/108512812370642528924/) on October 15, 2014 09:55:53_

1+

**Comment by prikhi** [comment]
_From [sarfa...@bluewire.com.pk](https://code.google.com/u/107255961999227443669/) on October 16, 2014 05:06:47_

1+

**Comment by prikhi** [comment]
_From [global...@gmail.com](https://code.google.com/u/103521020739213958677/) on November 11, 2014 11:33:05_

1+

**Comment by prikhi** [comment]
_From [interh...@gmail.com](https://code.google.com/u/112524659891601302557/) on January 28, 2015 11:22:32_

1+

**Comment by prikhi** [comment]
_From [adrian.h...@gmail.com](https://code.google.com/u/105292454498281309384/) on February 17, 2015 03:30:25_

1+

**Comment by prikhi** [comment]
_From [mikalai....@gmail.com](https://code.google.com/u/117556090463035274508/) on March 12, 2015 02:47:33_

1+

**Comment by prikhi** [comment]
_From [ville...@gmail.com](https://code.google.com/u/100530841611688647093/) on March 12, 2015 10:21:22_

1+

**Comment by prikhi** [comment]
One day I may get to this, but there is a lot to wade through - any help would be appeciated. Evolus still has their stencil development guide up:
http://pencil.evolus.vn/wiki/devguide/Introduction.html

**Comment by nathanielw** [comment]
Had been thinking I might give this a shot - I have [some experience](https://github.com/nathanielw/Android-Lollipop-Pencil-Stencils) making stencils and Bootstrap seem to have a decent overview of their components (http://getbootstrap.com/2.3.2/components.html).
I'd also be happy to help out updating the stencil dev docs (once #676 is complete I suppose) - I came across a few grammatical and technical errors when working my way through them.

**Comment by prikhi** [comment]
That'd be awesome! 

Much of my time has been spent reading, comprehending, fixing & cleaning all this code. So it'll probably be a while before I get ready to learn about & tackle issues for stencils - any help is appreciated :)

Don't feel obligated to wait for #676 to update the docs - anything changed in the repo will get updated when I convert everything. But don't feel obligated to do it now either... Just don't feel obligated in general :P

If you like, we could merge your Android stencils so they're included in every Pencil install. Although I've wondered why the original authors decided to [distribute zips of contributed stencils](https://code.google.com/p/evoluspencil/downloads/list?q=label:Stencil) instead of just merging them into the repo. Maybe there is a good reason for it, maybe not...

**Comment by nathanielw** [comment]
Sweet, happy to help and happy to see some life in Pencil again!

On the topic of merging stencils into the main package: the downside I see is that it makes it much harder for users to update stencils without having to get (or build) a new release of the entire app. It doesn't avoid the problem entirely, but I was thinking that perhaps additional built-in stencils could be included in the main repo via [Git submodules](http://www.git-scm.com/book/en/v2/Git-Tools-Submodules) - that'd allow stencil developers to continue work outside of the main repo (also allowing users to grab the latest zip of just a stencil collection) and just require the main repo to have `git submodule update` run every so often to keep things up-to-date.

Pipe-dream solution would be an online stencil registry that integrates with the app and allows for easy searching, installation and updating of stencils. That'd be a lot of work though!

**Comment by prikhi** [comment]
Yeah, I figured it might be easier for stencil maintainers if they were in a different repository. I was first thinking I could simply add the submodules under the appropriate directory in the `app` folder, but that wouldn't work for collections like your Material Icons - which need to be built. Maybe I'll modify the build script to download, include(and build, if necessary) any 3rd party stencils when building the application.

Do you know if it's possible for users to override a collection if the collection already exists within Pencil's code?

**Comment by nathanielw** [comment]
Ah, true, I hadn't considered collections that need to be built.

As for overriding an installed collection, it doesn't seem to work (even for user-installed collections) - it looks like Pencil checks for duplicates before installing the zip - around line 250 in [collectionManager.js](https://github.com/prikhi/pencil/blob/develop/app/content/pencil/definition/collectionManager.js#L250-L254). If you uninstall the collection first it works, but obviously bundled collections can't be removed.

**Comment by prikhi** [comment]
I've split those out into #677 and #678

**Comment by nathanielw** [comment]
Sweet. I've made a start on the Bootstrap stencil over at [nathanielw/Bootstrap-Pencil-Stencils](https://github.com/nathanielw/Bootstrap-Pencil-Stencils)
(not much to see yet)

**Comment by zenware** [comment]
What if stencil repositories just had a "built" branch and it would pull from that instead of the master branch.

**Comment by nathanielw** [comment]
(Added my thoughts on that in https://github.com/prikhi/pencil/issues/677#issuecomment-95446928)

**Comment by prikhi** [comment]
Closing, nathielw's stencil collection solves this :)
