### ISSUE TITLE
names conflict with Pencil Animation (www.pencil-animation.org)

### ISSUE THREAD

**Issue by prikhi** [prikhi/pencil#499]
_From [bartlomi...@gmail.com](https://code.google.com/u/112831051339036992004/) on October 24, 2012 11:27:13_

I can't install Evolus Pencil because it use the same name for folder, menu icon and program as Pencil Animation (www.pencil-animation.org)

folder: /usr/share/pencil
menu icon: /usr/share/applications/pencil.desktop
program: /usr/bin/pencil

Linux Mint 13 / Gnome 
evoluspencil_2.0.2-1_i386.deb

_Original issue: http://code.google.com/p/evoluspencil/issues/detail?id=499_

**Comment by prikhi** [comment]
_From [banzaimonkey](https://code.google.com/u/banzaimonkey/) on November 04, 2012 05:48:05_

I just encountered this too.

**Comment by prikhi** [comment]
Although now I'm thinking maybe this wasn't necessary...

It seems like pencil-animation turned into pencil2d & started storing stuff in /opt/ instead of /usr/.

Does anyone still need this?

**Comment by ReadyPlayerNaN** [comment]
I suppose, that if you renamed the main binary and desktop file to `evolus-pencil` and `evolus-pencil.desktop`, it would be ok. 

Main data are stored in `/usr/share/evolus-pencil`, it does not conflict with anything.

**Comment by prikhi** [comment]
Well my now main concern is that this fork has nothing to do with Evolus, so I think it would be best to change it to pencil or pencil-prototyping or something along those lines. 

I did some more digging & the original pencil animation project the OP was submitting died & was forked into this: http://www.pencil2d.org/

I downloaded the package for the 0.5.4 release & it looks like the executable & the folder is named `pencil2d` now, so I think it is safe to switch back to using just `pencil` for the data - unless there is another linux app with the name `pencil`(I didn't find one on Arch or Nix).
