### ISSUE TITLE
Export to PNG don't work

### ISSUE THREAD

**Issue by prikhi** [prikhi/pencil#526]
_From [oleg.re...@gmail.com](https://code.google.com/u/103887712870554236677/) on January 15, 2013 17:06:07_

What steps will reproduce the problem? 1. create a new document
2. place something on the new page
3. file - export page as png - choose folder - save What is the expected output? What do you see instead? expected - PNG file
instead - only svg file, but not complete (for example: text in rectangles missing and background too) What version of the product are you using? On what operating system? Evolus Pencil v.2.0.3
OS - Ubuntu 12.04.1 LTS
Firefox - 18.0 Please provide any additional information below. export worked sometime ago (2-3 weeks).
i CAN export to pdf, but not to ODT ("Progress..." window hang)  :(

_Original issue: http://code.google.com/p/evoluspencil/issues/detail?id=526_

**Comment by prikhi** [comment]
_From [liviu.va...@gmail.com](https://code.google.com/u/101069742744526747466/) on January 21, 2013 23:09:56_

same problem on version 2.0.4, running on Fedora 17
Export to pdf works.
Export to: odt, png, single web page doesn't - progress window hangs.
Everything worked fine a few weeks ago.

**Comment by prikhi** [comment]
_From [mcjo79@gmail.com](https://code.google.com/u/mcjo79@gmail.com/) on February 11, 2013 01:08:29_

same problem.
And the pdf export is not complet. The table/Tree is not exportable.

Using Ubuntu 12.04 x86-64.

**Comment by prikhi** [comment]
_From [physics...@gmail.com](https://code.google.com/u/110588020851540569930/) on March 10, 2013 10:01:03_

Fedora 17 , version 2.0.4 , xulrunner:Mozilla XULRunner 18.0.2 - 20130206130216
Fedora 18 , version 2.0.4 , xulrunner:Mozilla XULRunner 19.0 -20130218162742

can't export document to png on upon two environment.

A:  <Menu> --> Export Page as PNG --> choose a file --> save --> then nothing changes.
B:  <Menu> --> Export Document --> Rasterized graphics (PNG files) --> select any "Pages" to export --> Next --> Browse to select a destination --> finish --> Progress bar doesn't change.

**Comment by prikhi** [comment]
_From [physics...@gmail.com](https://code.google.com/u/110588020851540569930/) on March 11, 2013 02:42:29_

Hello , It seems that i have solved this problem.
the reason why can't save the png because the nsIWebBrowserPersist require 7 parameters on some xulrunner. 

so,correct it is easy :
find 264 line in svgRasterizer.js , change the following line
persist.saveURI(uri, null, null, null, null, localFile); 
to 
persist.saveURI(uri, null, null, null, null, localFile , null );

restart pencil , it works!

**Comment by prikhi** [comment]
_From [lorenzo....@gmail.com](https://code.google.com/u/118204882016606382139/) on March 11, 2013 04:07:11_

your suggest does not work for me.

**Comment by prikhi** [comment]
_From [physics...@gmail.com](https://code.google.com/u/110588020851540569930/) on March 11, 2013 05:46:38_

have you try this:
  /usr/lib/xulrunner/xulrunner --app /usr/share/pencil/application.ini -purgecaches

**Comment by prikhi** [comment]
_From [bra...@gmail.com](https://code.google.com/u/114488608460626527619/) on March 11, 2013 06:07:24_

Working for me :-) thank !

**Comment by prikhi** [comment]
_From [bra...@gmail.com](https://code.google.com/u/114488608460626527619/) on March 11, 2013 06:10:16_

Updated : https://bugzilla.redhat.com/show_bug.cgi?id=920043 and switched priority to high.

**Comment by prikhi** [comment]
_From [pisande...@gmail.com](https://code.google.com/u/107201758621820303583/) on April 16, 2013 07:28:05_

This suggest doesn't work for me either.
I tried the purge, but maybe there is something wrong...
"Command not found"

:(

**Comment by prikhi** [comment]
_From [fhernand...@gmail.com](https://code.google.com/u/103504767412118170046/) on April 30, 2013 13:09:16_

Hi! I had the same the issue after upgrading my archlinux system. 

First I was not able to open evolus-pencil because xulrunner-bin was not found. 
xulrunner-bin belongs to the version 14.*. So, I changed the execution of that file to the newest version of it wich is located in /usr/lib/xulrunner-devel-20.0/bin/xulrunner --app "$APP_INI", in /usr/lib/evolus-pencil-svn/evolus-pencil.sh.

Second issue arises after this fix, when Gecko attempts to load that version of xulrunner, so I changed to MaxVersion=20.\* in /usr/lib/evolus-pencil-svn/app/application.ini.

At this point evolus-pencil is running fine.

Finally when I attempted to export to any different format, evolus-pencil fails as this thread reports the issue.
It was fixed thank's to the suggestion `#4`.

find 264 line in svgRasterizer.js , change the following line
persist.saveURI(uri, null, null, null, null, localFile); 
to 
persist.saveURI(uri, null, null, null, null, localFile , null );

Thank's :)

**Comment by prikhi** [comment]
_From [coryd...@gmail.com](https://code.google.com/u/113502602137131383073/) on August 10, 2013 01:33:50_

This bug has been around forever. It's basically a critical defect, there's not much point in having a diagram you can't export. Any progress?

**Comment by prikhi** [comment]
_From [coryd...@gmail.com](https://code.google.com/u/113502602137131383073/) on August 10, 2013 01:38:28_

Also, FYI the svgRasterizer.js fix does not work for me on Ubuntu 13.04; otherwise all the symptoms are as reported.

**Comment by prikhi** [comment]
_From [step.to....@hotmail.com](https://code.google.com/u/107119267584566250254/) on August 13, 2013 22:38:44_

same problem 
fedora 19
firefox 21
export pdf works,can not get a png file

**Comment by prikhi** [comment]
_From [psaml...@gmail.com](https://code.google.com/u/111509506495295178961/) on August 19, 2013 02:47:38_

Experiencing this problem too, for several months. No error message.

Here's my environment:
- pencil 2.0.4 (distribution package) 
- Fedora release 19
- Linux 3.10.4-300.fc19.x86_64
- Mozilla XULRunner 23.0 - 20130805131520
- Firefox 23

Everything is working well on windows.

Fix suggested on comment https://code.google.com/p/evoluspencil/issues/detail?id=526#c6 did not work.

Kind regards

**Comment by prikhi** [comment]
_From [psaml...@gmail.com](https://code.google.com/u/111509506495295178961/) on August 19, 2013 08:37:04_

SVG export is working well too.

**Comment by prikhi** [comment]
_From [playes...@gmail.com](https://code.google.com/u/111172608279705600002/) on September 18, 2013 03:54:58_

For those with the "Command not found" problem you can do:
/usr/bin/firefox --app "/usr/share/pencil/application.ini" -purgecaches
instead.

That and change line 264 line in /usr/share/pencil/content/pencil/common/svgRasterizer.js from
persist.saveURI(uri, null, null, null, null, localFile); 
to 
persist.saveURI(uri, null, null, null, null, localFile , null );
did the trick for me.

I use Ubuntu 12.04 and I'm using pencil v2.0.3.

**Comment by prikhi** [comment]
_From [heiko.ma...@gmail.com](https://code.google.com/u/101481195773088773413/) on September 18, 2013 05:42:14_

Thanx to `#17` - this does the trick!!!

:-)

**Comment by AtillaSE** [comment]
This problem is still going on... Is it safe to assume this project is dead? 

I made a simple PHP file I put in every Document Export:

` <?php
exit( str_replace( '%5C', '/', file_get_contents( 'index.html' ) ) );`

then put an .htaccess in the root of all exports:

`DirectoryIndex index.php`

This will fix the problem with the documents not loading the PNG files...

**Comment by prikhi** [comment]
@AtillaSE Pretty much doing minimal maintenance at this point. Would accept a PR if you can fix this issue. Otherwise checkout out Pencil 3: http://github.com/evolus/pencil
