### ISSUE TITLE
table does not render properly when file re-opened

### ISSUE THREAD

**Issue by prikhi** [prikhi/pencil#534]
_From [Algorith...@gmail.com](https://code.google.com/u/117160764660029590483/) on February 03, 2013 23:07:18_

What steps will reproduce the problem? 1. re-open a page with a table on it
2. table displays first column heading and no data or other columns
3. double click table
4. click out of table
5. click table (now it will display properly) What is the expected output? What do you see instead? Table should render properly when file is opened What version of the product are you using? On what operating system? 2.0.3 Tested on Ubuntu 12.10 and 13.04

_Original issue: http://code.google.com/p/evoluspencil/issues/detail?id=534_

**Comment by prikhi** [comment]
_From [takes...@gmail.com](https://code.google.com/u/112827489695545853074/) on September 29, 2013 00:27:02_

my os: xubuntu 13.04 64bit
pencil: 2.0.5
see my attach jpg.

**Attachment:** [display1.jpg](http://code.google.com/p/evoluspencil/issues/detail?id=534#hc1)

**Comment by prikhi** [comment]
_From [takes...@gmail.com](https://code.google.com/u/112827489695545853074/) on September 29, 2013 00:56:06_

in fact, this problem just use 'Desktop - Navtive UI Widgedts'

**Comment by prikhi** [comment]
_From [tevoraen...@gmail.com](https://code.google.com/u/109755370789973797974/) on November 22, 2013 10:06:01_

I was using the version prior to 2.0.5.  Once I loaded the the 2.0.5 and opened a project I had created prior I am having the rendering issue mentioned above.  The Table/tree is from 'Desktop - Navtive UI Widgedts' is what I am having the problem with.  Is there any solution for this?  Otherwise I will probably go back to the last version.

**Comment by aligundogdu** [comment]
Hi im using versiyon 2.0.5
The problem still continues

**Comment by prikhi** [comment]
Are you using the Native GUI stencil collection?
This is a big issue & pretty much the highest priority: #602

**Comment by aligundogdu** [comment]
Yes
i use native gui.

**Comment by prikhi** [comment]
OK I'm gonna close this as a dupe of #602
