### ISSUE TITLE
evolus is not GPL !

### ISSUE THREAD

**Issue by prikhi** [prikhi/pencil#541]
_From [mathieu.malaterre](https://code.google.com/u/mathieu.malaterre/) on February 12, 2013 10:21:42_

evoluspencil is released under GPL, however this is not possible since Base64.js is relased under CC-BY 2.0/UK license: http://www.gnu.org/licenses/license-list.html#ccby and base64.js is released under: http://www.webtoolkit.info/license Thanks

_Original issue: http://code.google.com/p/evoluspencil/issues/detail?id=541_

**Comment by prikhi** [comment]
_From [mathieu.malaterre](https://code.google.com/u/mathieu.malaterre/) on February 12, 2013 07:22:21_

This prevents from having evolus in debian: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=628285#26

**Comment by prikhi** [comment]
_From [mathieu.malaterre](https://code.google.com/u/mathieu.malaterre/) on February 25, 2013 09:02:35_

This one is BSD and thus compatible: https://github.com/mshang/base64-js/blob/master/base64.js

**Comment by mvdw** [comment]
The result of git grep Base64:

```
app/content/pencil/bindings/clipartBrowserPane.xbl:                                //img._png = Base64.encode(png, true);
app/content/pencil/bindings/clipartBrowserPane.xbl:                                //debug("getMetadata - d: " + Base64.encode(img._png, true));
app/content/pencil/bindings/pCanvas.xbl:                            var base64 = Base64.encode(bytes, true);
app/content/pencil/bindings/privateCollectionPane.xbl:                            var base64 = Base64.encode(bytes, true);
app/content/pencil/common/base64.js:*  Base64 encode / decode
app/content/pencil/common/base64.js:var Base64 = {
app/content/pencil/common/base64.js:                    input = Base64._utf8_encode(input);
app/content/pencil/common/base64.js:                    output = Base64._utf8_decode(output);
app/content/pencil/stencilGenerator.js:                        var data = Base64.encode(fileData, true);
```

Only the encode function is ever used. 
So it should indeed be easy to replace this.
