### ISSUE TITLE
Saved mockups (or copy/pasted elements) don't render completely

### ISSUE THREAD

**Issue by prikhi** [prikhi/pencil#579]
_From [rossetti...@gmail.com](https://code.google.com/u/115673868205892094406/) on August 27, 2013 05:56:29_

What steps will reproduce the problem? 1. Create a mockup using the Native UI Widgets
2. You can either copy and paste an element or save the mockup, close Pencil, open it and load the saved mockup 3. What is the expected output? What do you see instead? I expect the copy/pasted or saved/opened UI mockup to be rendered as it is supposed to be. Instead I have no text and most UI elements don render completely or at all. What version of the product are you using? On what operating system? 2.0.3 standalone and I also tried the Firefox version. I tried this on two different PCs just to make sure it wasn't a particular install. Both PCs run Ubuntu Linux 13.04 with all updates. Please provide any additional information below. Both machines are 64bit, both use java (OpenJDK) version "1.6.0_45" 64bit (not sure if Java is needed), I also tried version "1.7.0_25" with no change. I tried running the same test with the sketchy UI element and it does not have this problem. I attached 2 screenshots, one of how it is when designed. The other is of the saved and re-opened mockup. This issue makes it unusable (not to mention I lost several hours of work). Thank you for looking into this.

**Attachment:** [before_save.png after_save.png](http://code.google.com/p/evoluspencil/issues/detail?id=579)

_Original issue: http://code.google.com/p/evoluspencil/issues/detail?id=579_

**Comment by prikhi** [comment]
_From [rossetti...@gmail.com](https://code.google.com/u/115673868205892094406/) on August 27, 2013 05:02:17_

An update, I was able to open the file on a friend's computer on Windows.

**Comment by prikhi** [comment]
_From [gigab...@gmx.net](https://code.google.com/u/114959428936113136182/) on August 28, 2013 01:57:14_

Same for me - but does not only effect rendering after reopen, but also export / print.
serious bug in my opinion, makes the whole project useless.

**Comment by prikhi** [comment]
_From [gigab...@gmx.net](https://code.google.com/u/114959428936113136182/) on August 28, 2013 02:20:42_

issue seems to be related to 2.0.3 only.
after uninstalling 2.0.3, and using evoluspencil_2.0.2_amd64.deb, rendering was OK.
Seems to be related to issue #554 -     export to png dosn't work  ?

**Comment by prikhi** [comment]
_From [lennartw...@googlemail.com](https://code.google.com/u/107515343746468900891/) on June 25, 2014 01:15:46_

This bug still exists in 2.0.5. Resizing a widget fixes the issue. That does not help much, because each widget need to be resized separately.

**Comment by prikhi** [comment]
_From [napper...@gmail.com](https://code.google.com/u/114532926598605760968/) on July 09, 2014 19:43:58_

Does Pencil still use XUL for the UI? Have exactly the same issues with using Pencil 2.0.5. Rendering issues aren't isolated to a single version of Pencil.

Is there a way to force Pencil to do a refresh per Page? Not the best workaround if one exists, but it would greatly reduce the amount of work needed to have all Pages rendered properly.

**Comment by prikhi** [comment]
_From [hett...@gmail.com](https://code.google.com/u/114347103855161859183/) on September 08, 2014 00:33:11_

Same here in 2.0.5, Windows 7 Pro 64 bit. Same problem by using Sketchy gui widget as well. All containers with text appear empty after open. Resizing or double-clicking on them helps, temporarily.

**Comment by prikhi** [comment]
_From [MacheteP...@Live.com](https://code.google.com/u/103575885777876909353/) on September 08, 2014 11:41:45_

This was issued over a year ago and I am still having the same problem. I know its free open source, but honestly, is this how you want your quality represented?

**Comment by prikhi** [comment]
_From [Serg.Def...@gmail.com](https://code.google.com/u/107678813295086852148/) on September 23, 2014 21:26:55_

The same issue.
2.0.5. Win 8.1 x64

**Comment by prikhi** [comment]
_From [demonuc...@gmail.com](https://code.google.com/u/115120339270499663089/) on October 01, 2014 12:11:59_

Experience the same on Win7 64 bit, evoluspencil v2.05.
Very annoying.

**Comment by prikhi** [comment]
_From [mariasjo...@gmail.com](https://code.google.com/u/101035142878227901041/) on January 22, 2015 04:01:52_

I have the same problem. Windows 7 and 2.0.5
It's a showstopper for me and it's a real pity that it's not fixed for over a year. I will have to buy some other software now.

**Comment by prikhi** [comment]
_From [mariasjo...@gmail.com](https://code.google.com/u/101035142878227901041/) on January 22, 2015 04:11:51_

A little workaround I found. If you only use the GTK Widgets it seems to work. I only get the problem with Native UI Widgets.

**Comment by prikhi** [comment]
_From [Tim.Bied...@gmail.com](https://code.google.com/u/116390683615762617424/) on February 17, 2015 00:51:17_

I have the same Problem win 8.1 64bit and 2.0.5
downgrade to 2.0.2 and it works

**Comment by prikhi** [comment]
_From [c...@dunravensystems.com](https://code.google.com/u/118004496983180903977/) on February 18, 2015 03:41:04_

2.0.5, Windows 8.1 64 bit.
As said, this is a show-stopper for an otherwise pretty good application.

**Comment by prikhi** [comment]
#602

**Comment by galvani** [comment]
Just don't use native UI widgets.
