### ISSUE TITLE
2.0.6 in OS X not honoring ⌘-a shortcut

### ISSUE THREAD

**Issue by prikhi** [prikhi/pencil#665]
_From [paul.ign...@gmail.com](https://code.google.com/u/115221069588251903258/) on January 11, 2015 03:22:17_

What steps will reproduce the problem? 1. Press ⌘-a What is the expected output? What do you see instead? The expected out put is selecting all items same as using the menu. I see the edit menu flash instead and nothing is selected. What version of the product are you using? On what operating system? 2.0.6 on OS X Yosemite.

_Original issue: http://code.google.com/p/evoluspencil/issues/detail?id=665_

**Comment by dingus9** [comment]
Confirmed: ⌘-a(select all) is not working correctly on OSX:
2.0.15.20151201 OSX El Capitan 10.11.1

Expected behavior would be the same as selecting "Edit->Select all".
All other shortcuts seem to work under "Edit"

**Comment by prikhi** [comment]
This is strange as the select-all key is defined in the same way as cut, copy, paste:
https://github.com/prikhi/pencil/blob/develop/app/content/pencil/mainWindow.xul#L413
https://github.com/prikhi/pencil/blob/develop/app/content/pencil/mainWindow.xul#L605

except for the fact that the other commands define a `command` while select all uses the `oncommand`. I tried making a command for selectAll, I doubt it will fix anything, but if possible can you try running Pencil from the [fix-osx-select-all](https://github.com/prikhi/pencil/tree/fix-osx-select-all) branch? You might have to delete the cached files in `~/Library/Pencil` first.

**Comment by dingus9** [comment]
The menu item seems to work fine, just not the command-A shortcut... I built the project with ./build.sh mac off of the fix-osx-select-all branch. Hoping that is the correct process to test this stuff.

**Comment by dingus9** [comment]
Fixed it, the selectAllKey was missing command="selectAllCommand".

**Comment by dingus9** [comment]
PR #774 waiting for review.

**Comment by prikhi** [comment]
Thanks for this, should be able to test on linux/windows today
