### ISSUE TITLE
Migrate Docs to Sphinx/reStructuredText

### ISSUE THREAD

**Issue by prikhi** [prikhi/pencil#676]
The files under `/docs/` are pure HTML. 

I'd like to convert them to Sphinx so we can host them on RTD:

http://sphinx-doc.org/
http://sphinx-doc.org/domains.html#the-javascript-domain
http://sphinx-doc.org/config.html#confval-primary_domain
http://rtfd.org/

**Comment by Zyzle** [comment]
I came across this project a few days ago looking at Pencil on Google Code.  I've been having a read through the documentation trying to understand how the application works and hopefully contribute something back to the project.

I've started to take a look at migrating the existing documentation into Sphinx and will make a pull request when the initial batch is done.

**Comment by prikhi** [comment]
Hooray! I appreciate any time spent on this :)

For setting up the initial structure, see: http://sphinx-doc.org/tutorial.html
Most of the docs will most likely be just plain RST: http://sphinx-doc.org/rest.html
Although additional Sphinx constructs may be useful: http://sphinx-doc.org/markup/index.html

You can ignore all the autodoc, cross-referencing & javascript domain stuff for now(although if `sphinx-quickstart` asks please switch the default domain to javascript).

Thanks & let me know if you run into any problems!

**Comment by Zyzle** [comment]
I've got the basic devguide and tutorials pages converted just need the inter-page links and images in and can then make a start on the reference. This'll probably take a bit longer but should be able to get some done soon.

**Comment by prikhi** [comment]
Awesome!

For links to sections, I'd recommend adding a label before the section header & linking to that using `ref`, instead of using rst links.

From: http://sphinx-doc.org/markup/inline.html#ref-role

```
Using ref is advised over standard reStructuredText links to sections (like
`Section title`_) because it works across files, when section headings are
changed, and for all builders that support cross-references.
```

**Comment by prikhi** [comment]
Live at http://pencil-prototyping.rtfd.org
Gonna do a little cross-referencing & re-organization before closing this.

**Comment by nathanielw** [comment]
Looking good!
I made a bunch edits to the HTML version (fixing up numerous grammatical errors), but didn't get it pushed anywhere before I saw that @Zyzle had made a start on the Sphinx port. I can try and get a pull request up for those asap.

One request: would it be possible to have the tutorial pages listed in the sidebar? I find myself jumping between all those pages when developing, so it's handy to have them all accessible from each other.

**Comment by prikhi** [comment]
Welp that last commit makes it show tutorial pages in the sidebar when you build them locally - for some reason RTDs doesn't pick up the template override. I will investigate...

**Comment by prikhi** [comment]
@nathanielw The online docs now have the sidebar nesting you requested: https://pencil-prototyping.readthedocs.org/en/latest/devguide/tutorial/index.html

I've also reviewed & added cross-references to the Reference guide.

I think that pretty much wraps up this ticket, but I haven't developed a Stencil yet so I don't know what would be super useful to include. Additional feedback welcome, otherwise I'll close this off in a couple of days.

**Comment by nathanielw** [comment]
Awesome, thanks for that.
I think the docs at the moment do a good job of covering Stencil creation, so as far as I'm concerned, nothing more is needed at the moment.

**Comment by prikhi** [comment]
At some point I'll move the less useful docs out of the readme & into sphinx(like maintainer-only info), but I'm going to go ahead & close this now.
