### ISSUE TITLE
Linux build failure when not using bash

### ISSUE THREAD

**Issue by Zyzle** [prikhi/pencil#682]
The current build script uses 

``` bash
#!/bin/sh
```

However the syntax used in the Linux build section:

``` bash
echo "Creating directory structure..."
mkdir -p $OUTPUT/usr/{bin,share/{$PKG_NAME,applications,mime/packages}}
```

uses bash specific syntax and will fail if the systems default shell is not set to bash.  For example the Ubuntu default shell has been dash since 6.10 (8.04 for LTS)

A quick fix would be to change the she-bang line to:

``` bash
#! /bin/bash
```

as most systems should have bash installed even if it isn't the default environment shell

**Comment by prikhi** [comment]
Thanks
