### ISSUE TITLE
Font Weights not supported

### ISSUE THREAD

**Issue by gyanl** [prikhi/pencil#693]
The only variant of Roboto I can see is the standard one, and it's hard to design an app ui without black/light/thin variants.

I just realised this is already addressed in #667, sorry for the duplicate.

**Comment by prikhi** [comment]
> I just realised this is already addressed in #667, sorry for the duplicate.

It's OK, the majority of the 500 or so issues on here were imported from Evolus' old bug tracker, so any confirmation that those issues are still occurring is helpful.

That said, I'm closing this as a duplicate, marking #667 as confirmed & assigning it to milestone v2.1.0, please subscribe to #667 if you want updates.
