### ISSUE TITLE
How to clear the cache?

### ISSUE THREAD

**Issue by steroides** [prikhi/pencil#697]
Hi,

Someone know how I can clear Pencil's cache (or just the XulRunner's cache)?

Thanks.

**Comment by steroides** [comment]
Solved. Just had to add the following in Evolus\Pencil\app\defaults\preferences\pencil.js:

pref("nglayout.debug.disable_xul_cache", true);
pref("nglayout.debug.disable_xul_fastload", true);

**Comment by prikhi** [comment]
If you're on Linux, you could try removing your `~/.cache/pencil` folder. There's profiles in `~/.pencil` as well.
