### ISSUE TITLE
glib problem？

### ISSUE THREAD

**Issue by fratcn** [prikhi/pencil#699]
here is the error imformation in the terminal：

> pencil
> (process:13819): GLib-CRITICAL *_: g_slice_set_config: assertion 'sys_page_size == 0' failed
> Error: Platform version '38.0.1' is not compatible with
> minVersion >= 36.0
> maxVersion <= 37._

**Comment by Zyzle** [comment]
38.0.1 is the recently released version of Firefox. If you're set up to
receive automatic updates (the Firefox default) then your system probably
updated a few days ago. The min and max versions are set in pencils
configuration. You could try increasing the max version and see if it still
runs.

The config lines can be found in: 
[pencil/build/properties.sh](https://github.com/prikhi/pencil/blob/3962b7d92f09f7e7ee77ea2703de233b0edfea6c/build/properties.sh#L8-L9)

**Comment by prikhi** [comment]
The latest release(v2.0.11) fixes this.
