### ISSUE TITLE
communication among contributors 

### ISSUE THREAD

**Issue by jdittrich** [prikhi/pencil#709]
It would be great to have some form of communication between contributors (and possibly users too). I suppose the easiest would be opening a room on [gitter.im](https://gitter.im) which can be created @prikhi (aka repo owner) and used by anyone with a github account. 

Alternatives would be a mailinglist or a freenode IRC channel.

**Comment by prikhi** [comment]
#713 Added the gitter badge. Should I add anything else?

**Comment by jdittrich** [comment]
Thanks, thats fine. I’ll close it for now, if we want we can add some stuff later if needed.
