### ISSUE TITLE
Packaging: Linux path is /usr/share/evolus-pencil

### ISSUE THREAD

**Issue by mvdw** [prikhi/pencil#726]
In version 2.0.5, the path where pencil was installed was:
  /usr/share/pencil
In our version it is:
  /usr/share/evolus-pencil
That is a pity. I think there are reasons for not using "pencil2 as path - there are other applications named "pencil" and that could give a conflict (this is just a thought - anyone can confirm?).

I propose to rename this directory to 
  /usr/share/prikhi-pencil
Any thoughts?

This is not urgent, it works as is now.

**Comment by prikhi** [comment]
I changed it because the pencil2d animation software was installing under `/usr/share/pencil` on debian. I think they now use `pencil2d` instead so it should be OK to switch it back. See #499 instead.
