### ISSUE TITLE
Palemoon support

### ISSUE THREAD

**Issue by zindy** [prikhi/pencil#743]
As per https://forum.palemoon.org/viewtopic.php?t=5440 I added a palemoon section in install.rdf

```
<!-- Pale Moon -->
<em:targetApplication>
  <Description>
    <em:id>{8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}</em:id>
    <em:minVersion>25.0</em:minVersion>
    <em:maxVersion>25.*</em:maxVersion>
  </Description>
</em:targetApplication>
```

And that was enough to make Pencil 2.0.13 work in Palemoon 25.7.0

**Comment by mikedlr** [comment]
@zindy are you able to put that as a pull request and link it to this issue please?

**Comment by prikhi** [comment]
Bout to release a new version, will try to get this in.

**Comment by prikhi** [comment]
This exists & should be supported in the github & mozilla XPI files in the next version.

Should I add anything in the Readme with respect to Palemoon before closing this?

**Comment by prikhi** [comment]
OK did more reading, looks like exporting won't work because of breaking changes mozilla make to FFv38. People have asked for me to support a lower version of FF/XRE before, I will investigate.

**Comment by prikhi** [comment]
Exporting now works in Palemoon as of v2.0.21. You should also be able to install it from the firefox addons page: https://addons.mozilla.org/en-US/firefox/addon/pencil-prototyping/

**Comment by prikhi** [comment]
Also issue #802 does not occur when using with Palemoon.
