### ISSUE TITLE
Binary package for Debian

### ISSUE THREAD

**Issue by aleksandaratanasov** [prikhi/pencil#752]
For installation on a Debian system you can use the **ubuntu-all** binary package. To work around the issue with detection of **Iceweasel** see [this post](https://code.google.com/p/evoluspencil/issues/detail?id=556). I suggest fixing this in this repository. For Debian Jessie my **control** for the package looks like this:

```
Package: pencil
Version: 2.0.14
Section: devel
Priority: optional
Architecture: amd64
Depends: firefox (>= 36.0) | iceweasel (>= 38.0)
Installed-Size: 9216
Maintainer: Pavan Rikhi <pavan.rikhi@gmail.com>
Description: GUI Prototyping/Wireframing
 Pencil is a multiplatform tool for GUI Prototyping/Wireframing
```

Debian Jessie has Iceweasel 38.2 in upstream. You can change the version to a lower if you need to. This should also work on a Debian Wheezy.

**Comment by prikhi** [comment]
Can you try installing this package and let me know if it works OK:
https://www.dropbox.com/s/jypxqi5hzv1alq5/pencil-2.0.14-ubuntu-all-debian-fix.deb?dl=0

**Comment by aleksandaratanasov** [comment]
Yeap, removed my package and installed yours. No problem detecting Iceweasel. Btw. I saw you have used `>= 36.0` for the Iceweasel dependency. If someone has older Debian and can test a lower version of Iceweasel it would be great if we lower the version for this dependency even more so that older systems can use it out of the box.

**Comment by prikhi** [comment]
Awesome, I'll go ahead an merge it.

Unfortunately, using a version lower than 36 breaks all export methods:(
