### ISSUE TITLE
add a package image/icon for pencil application

### ISSUE THREAD

**Issue by auvipy** [prikhi/pencil#764]

**Comment by igpremuo** [comment]
If you are using linux, the problem is in the icon path. 

Modify the file `/usr/share/applications/pencil.desktop` and change the next line:

```
Icon=/usr/share/evolus-pencil/skin/classic/icon.svg
```

by this one:

```
Icon=/usr/share/pencil/skin/classic/icon.svg
```

**Comment by prikhi** [comment]
Thanks for catching that @igpremuo

**Comment by prikhi** [comment]
Oops, actually that only applies for debian builds. I'll move all linux builds to either `pencil` or `pencil-prototyping` before the next release...

**Comment by prikhi** [comment]
#499
