### ISSUE TITLE
Pencil 2.0.15 not working with Firefox 43 on Mint

### ISSUE THREAD

**Issue by ahaqxjl** [prikhi/pencil#777]
I have pencil 2.0.15 runing on Mint 17.3, it is installed from [pencil-2.0.15-ubuntu-all.deb](https://github.com/prikhi/pencil/releases/download/v2.0.15/pencil-2.0.15-ubuntu-all.deb), and I upgrage firefox from 42 to 43 yesterday.

Now when I run pencil, it says:

```
Error: Platform version '43.0' is not compatible with
minVersion >= 36.0
maxVersion <= 42.*
```

I thought it should support firefox >= 36.0 as in README of pencil:

> You will need version 36 or higher of firefox to run Pencil as a Firefox Extension. Linux users will need version 36 of either firefox, iceweasel or xulrunner.

What should I do? Edit any configuration file of pencil to make it support firefox43 or downgrade firefox in Mint to 42? Please provide detail steps.

**Comment by ahaqxjl** [comment]
I currently edit pencil settings to make it support firefox 43, I need it working since I want to submit one prototype to customer TODAY, but I am not sure if there is any potential problem.

```
sudo vim /usr/share/pencil/application.ini
```

change `maxVersion=42.*` to `maxVersion=43.*`

**Comment by prikhi** [comment]
Hi, changing the max version should be fine. It's been done on the `develop` branch already.

I'm not at home and my laptop's distro(NixOS) doesn't have everything to make a new release on the `master` branch - so it'll have to wait til the 29th or so, or I'll have to write a package for `nsis`.

**Comment by matjack1** [comment]
Same problem here and increasing `MaxVersion` to 43 works fine.

**Comment by mnagel** [comment]
why is it necessary to specify the MaxVersion so conservatively?
Putting 43 there will fix it for now, but it will break again with Firefox 44, am I right?

**Comment by Tynach** [comment]
44 is out, and no new version of Pencil has been released to address anything newer than 42. Firefox releases occur too rapidly for this :/

**Comment by prikhi** [comment]
AMO will automatically reject the plugin if the MaxVersion is too high. Went ahead & tested on FF Developer so should be good til v46 now.

**Comment by prikhi** [comment]
(new release on the way)
