### ISSUE TITLE
No way to install this on Ubuntu 15.10 (Deb) or Firefox 43

### ISSUE THREAD

**Issue by jasiralavi** [prikhi/pencil#778]
Unable to install this on the latest latest ubuntu (15.10) either directly or as Firefox addon.
1. While trying to install the Deb file, it gives a bad file permission error and prevents from installing
2. Firefox 43 won't let the addon be installed because it's not signed
3. There is also a name conflict in Ubuntu repos with a cartoon application having the same name (Pencil)

These are important for linux/debian/ubuntu users to just get to install this great software. Hope these can be marked urgent and sorted out soon.

**Comment by mohammadrafigh** [comment]
I agree that.

**Comment by prikhi** [comment]
for now you can disable extension signing by toggling `xpinstall.signatures.required` in `about:config`

first priority for installs will be getting the unlisted XPI signed while we wait for the listed one to be reviewed. then I'll poke around debian installs. Might be a little while, on the road so I can't spin up a ubuntu VM to play around w/ it.

**Comment by jasiralavi** [comment]
Thanks for getting it fixed on firefox, prikhi.

For those who're looking for it on firefox addons, here's the direct link:
https://addons.mozilla.org/en-US/firefox/addon/pencil-prototyping/

**Comment by parthlawate** [comment]
Hi 

I found your issue on Debian (i think) . Your package name conflicts with another ubuntu/debian app.. Change the first line of the control file (/pencil-2.0.15-ubuntu-all/DEBIAN/control) to 

Package: pencil to > Package: evoluspencil

**Comment by jasiralavi** [comment]
I've added some details about the conflict under issue #748

**Comment by parthlawate** [comment]
This PR soves this issue atleas for Ubuntu . please test https://github.com/prikhi/pencil/pull/781
