### ISSUE TITLE
i386 package

### ISSUE THREAD

**Issue by jniggemann** [prikhi/pencil#794]
Good to see this project being picked up, thank you for your work.
Can you please also create and distribute a i386 deb? There are still machines out there running i386...

**Comment by prikhi** [comment]
Should be possible by just changing `architecture` in `builds/Ubuntu/control` to `any` or `all`. The initial PR had it set to `amd64` & I didn't catch it, sorry about that.

Grabbing Ubuntu i386 right now so I can test it out first.

**Comment by jniggemann** [comment]
No problem, thank you!
