### ISSUE TITLE
I don't know what to dowload to get Pencil started?

### ISSUE THREAD

**Issue by jackfunkinstain123** [prikhi/pencil#797]
Hi, Prikhi,
I am new to website design and know very little about using programs that aren't already functional on their own. I understand that this issue page isn't for beginner questions like this so I apologize.
Is there a better way to contact you? 
I don't know what I need to download to get Pencil Started.
My operating system is Windows Vista, 32bit

quote-"You'll need **curl** installed so you can pull the Windows XULRunner runtime and **NSIS** to compile the installer."

I don't know what Curl file to install? Will it automatically pull windows XULRunner runtime?
Which version of NSIS do I need? NSIS 2.50 or NSIS 3.0b3? Will it compile the installer automatically?

Will the latest v2.0.16 release have all the Templates, stencils, ect. or do I need to download those separately? and will I have to continuously download the latest release of pencil to get updates and bug fixes (and will that just update the version I already have ) or do I need to download updates on their own? 

I was planning on using the "Pencil-2.0.16-win32.installer.exe" but I was wondering what is the difference/benefits of "Pencil-2.0.16-firefox.xpi"? will all my stuff be saved on a firefox cloud? Can I still save projects on my computer?

I notice that there are continues bugs that need to be fix as more features are added, Can my pc or browser be damaged from Bugs.

Thank you in advanced, I think it's great you are developing a website/app designer tool that is free

**Comment by mikedlr** [comment]
Hi @jackfunkinstain123 ; you need to read a bit down in the main README file,  there you can find the link to a ready to go windows installer.    I don't know of another support forum than this.  If you have time it might be nice to start one.  

I have put in a pull request to make the link more obvious.  This should request should now be closed.

**Comment by prikhi** [comment]
XPI is the application as a firefox addon, EXE is the application as a native Windows program. I don't use Firefox Cloud or know how it works so I can't comment on that, but both versions should let you save to the current computer.

I merged the PR by @mikedlr and added a link to Mozilla's Addon Repository as well.

Also,  there is Google Group from the old Evolus Pencil that you can use:
https://groups.google.com/forum/#!forum/pencil-user
