### ISSUE TITLE
Firefox icon change

### ISSUE THREAD

**Issue by madvik** [prikhi/pencil#799]
The icon of firefox on windows is changed when we start the module.
But If I quit, the icon don't disappear.
![capture](https://cloud.githubusercontent.com/assets/3822529/13428330/0f92d71e-dfba-11e5-9b33-c969d981358d.JPG)

**Comment by mvdw** [comment]
I presume this issue is a duplicate of #742.

**Comment by madvik** [comment]
Sorry, I don't see this issue.
