### ISSUE TITLE
Useability Linux: marked text in text fields prevents paste from clipboard

### ISSUE THREAD

**Issue by Olli** [prikhi/pencil#804]
If a textfield should be filled with clipboard contents the clipboard contents got overwritten because the text in the textfield is marked. So it's been automatically copied to clipboard.
If the textfield lost focus it closes. 
Maybe this is a linux-only issue because of the special clipboard nature on X which instantly copies marked text into the clipboard.

**Comment by Olli** [comment]
Its an duplicate of #801 Ii think.

**Comment by jfouse** [comment]
@Olli no, this is completely unrelated to #801, which happens on Windows and has to do with focus change.  Nothing about the clipboard at all.
