### ISSUE TITLE
Not working area - 2.0.17

### ISSUE THREAD

**Issue by Mgldvd** [prikhi/pencil#806]
OS - Linux Mint 17.3
pencil-prototyping-2.0.17-ubuntu-all.deb

![pencil](https://cloud.githubusercontent.com/assets/2009698/13754741/80cf631e-e9ee-11e5-9231-3f6114afd491.png)

**Comment by prikhi** [comment]
Accidentally left a debug flag on when building the latest versions, 2.0.18 incoming soon.

**Comment by prikhi** [comment]
Can you test 2.0.18? 
https://github.com/prikhi/pencil/releases/tag/v2.0.18

**Comment by Mgldvd** [comment]
2.0.18 works fine :+1: 

![pencil](https://cloud.githubusercontent.com/assets/2009698/13758794/a1bd5df2-ea01-11e5-805c-dd836f2356ab.png)
