### ISSUE TITLE
downlaod of pencil for windows gives this error message

### ISSUE THREAD

**Issue by jonboybebop** [prikhi/pencil#808]
![image](https://cloud.githubusercontent.com/assets/17862292/13796460/c2222ffc-eafe-11e5-90de-bd54aafc2e22.png)

**Comment by prikhi** [comment]
That looks like Norton 360 Total Security, not a Windows pop-up. The files under the `xulrunner` directory are distributed by Mozilla. If you trust Mozilla, you should allow the installer to create those target files.

Another option is to install firefox then create a `.bat` file that runs `firefox.exe -app C:/path/to/pencil/folder/application.ini`.  Installing somewhere other than `C:\Program Files (x86)\` might also prevent this.

**Comment by jonboybebop** [comment]
k thank you
