### ISSUE TITLE
Ubuntu 16.04 with XULRunner 47.0a2

### ISSUE THREAD

**Issue by ajsb85** [prikhi/pencil#820]
``` sh
pencil-prototyping 
Error: Platform version '47.0a2' is not compatible with
minVersion >= 36.0
maxVersion <= 46.*

```

**Comment by legocef01** [comment]
download xulrunner version between 36 and 46 from here http://ftp.mozilla.org/pub/xulrunner/releases/

you should download the corresponding arch from runtimes/ directory

**Comment by ghost** [comment]
What am I supposed to do after I download stuff from there?
I'm on Ubuntu 16.04 64bit.

**Comment by legz** [comment]
A PR is pending.
In the meantime, here is a fix : edit /usr/share/pencil-prototyping/application.ini

```
-MaxVersion=46.*
+MaxVersion=47.*
```

**Comment by ghost** [comment]
thanks that did the trick for me.

**Comment by BJming** [comment]
thank you ,after fix /usr/share/pencil-prototyping/application.ini , I can use pencil prototyping
it's very cool .

**Comment by prikhi** [comment]
Should be fixed.
