### ISSUE TITLE
unable to 

### ISSUE THREAD

**Issue by tomkralidis** [prikhi/pencil#829]
OS: Windows 7
Installation: as FF plugin
FF: 46.0
Pencil version: 2.0.18.20160314

When opening a new or existing diagram, I am unable to drag shapes onto the main canvas.  Upon attempting to drag the shape, the mouse cursor changes to a "not allowed" icon (like :no_entry_sign:, but black)

**Comment by nvoynov** [comment]
Hello, 
I just install Pencil as FF plugin, Win10, FF 46.
I can't add any new object to any page, just as tomkralidis wroted before.

Standalone application works!

**Comment by ghost** [comment]
Same on Ubuntu 16.04. Is there a workaround?

**Comment by ccloli** [comment]
The same on Windows 8.1, Firefox 47.0

**Comment by prikhi** [comment]
See #802
