### ISSUE TITLE
FYI: Evolus Pencil v3.0.0 beta 1

### ISSUE THREAD

**Issue by shelleyvadams** [prikhi/pencil#836]
I just started using Pencil, so I was over at the Evolus site looking for stencils, and I noticed [a new version](http://pencil.evolus.vn/Next.html) dropped on Saturday (4 June).

New [development](https://github.com/evolus/pencil) is also here on GitHub; @mbrainiac appears to be project admin

Looks like there are lots of changes, but the biggest is probably dropping XUL for [Electron](http://electron.atom.io/).

**Comment by Zeitwaechter** [comment]
Update: v3.0.0 beta 2 since 2016-06-10 (http://pencil.evolus.vn/Next.html)

**Comment by lifan0127** [comment]
Just a few hours ago (2016-07-24)
v3.0.0 rc1 
https://github.com/evolus/pencil/releases/tag/v3.0.0-rc.1

**Comment by Zeitwaechter** [comment]
Ugh? They reverted to RC1? What's their big deal? o.O

**Comment by larvanitis** [comment]
Can we have an official word on whether this fork is going to stay as a separate project or is it going to be dropped / merged with the official Evolus release, which is now going for version 3?

**Comment by rsertelon** [comment]
@Zeitwaechter RC is generally after beta since it is a Release Candidate ;)

**Comment by strixaluco** [comment]
> or is it going to be dropped / merged with the official Evolus release

@larvanitis this fork (based on XUL) can't really be merged with Evolus's revival, as the latter is based on Electron.
And it looks like v3.0's development is also stalled for a while.

**Comment by prikhi** [comment]
I added a link to v3 in the readme. I'll keep maintaining this but probably won't do much more development. I get the "can't drag & drop" bug in v3, so I'm still using this with xulrunner/palemoon.
