### ISSUE TITLE
what is the newest version evolus pencil 2.0.5 or Pencil Prototyping 2.0.18??

### ISSUE THREAD

**Issue by John3** [prikhi/pencil#839]
HI,

what is the newest version evolus pencil 2.0.5 or Pencil Prototyping 2.0.18?? is very confuncing...  can we have in the wiki FQA this kind of questions?

What feature/fix have this pencil 2.0.5 or Pencil Prototyping 2.0.18?

And don't want the evolus v3 

thanks!

regards
J

**Comment by alexander-ae** [comment]
Releases -> https://github.com/prikhi/pencil/releases

**Comment by John3** [comment]
thanks
