### ISSUE TITLE
Error: Platform version '47.0' is not compatible with minVersion >= 36.0 maxVersion <= 46.*

### ISSUE THREAD

**Issue by zenny** [prikhi/pencil#840]
Firefox is in version 47, and it could be because of the reason that pencil v2.0.18 gives an error in Ubuntu 14.04:

> Error: Platform version '47.0' is not compatible with
> minVersion >= 36.0
> maxVersion <= 46.*

SOLUTION:

appended maxVersion to 47.\* in /usr/share/pencil-prototyping/application.ini

**Comment by dagomar** [comment]
Thanks,

this fixes pencil not starting up for me.

**Comment by bjornfor** [comment]
@prikhi: Is the OP solution sufficient? I'm trying to get pencil working in NixOS again; it's currently broken in both the latest stable and unstable releases, because both ship new firefox.

**Comment by Xplouder** [comment]
Thanks for the fix.

**Comment by vince-a** [comment]
Worked for me. Thanks.

**Comment by catb0t** [comment]
Works for me with the latest stable DEB on Ubuntu 16.04.

**Comment by cho2** [comment]
> SOLUTION:
> 
> appended maxVersion to 47.\* in /usr/share/pencil-prototyping/application.ini

Thanks, it works on Debian 8

**Comment by mnagel** [comment]
path is /usr/share/pencil/application.ini for me, but updating to 47.\* fixes the issue for me.
also see #777

**Comment by prikhi** [comment]
Fixed

**Comment by bjornfor** [comment]
@prikhi: Thanks. Pencil is updated to latest in NixOS/nixpkgs.

**Comment by MisterY** [comment]
For those who get to this issue through search engines and are looking for the solution for the newer versions, the application.ini is now in `/usr/share/evolus-pencil`.
