### ISSUE TITLE
2.0.18 Not working on Ubuntu 16.04

### ISSUE THREAD

**Issue by Defcon0** [prikhi/pencil#842]
Installing the latest *.deb has no success. When starting the application, nothing happens :(

**Comment by marius-bareisa** [comment]
In terminal, paste this:
**sudo gedit /usr/share/pencil-prototyping/application.ini**

then, in application.ini file, change the following:
_MaxVersion=46.*_
to
_MaxVersion=47.*_

source: https://github.com/prikhi/pencil/issues/840

**Comment by gsavvid** [comment]
Or to _MaxVersion=48.*_ if your Firefox's version is 48 like in my case.

**Comment by dweremeichik** [comment]
@ne2rnas @gsavvid Does it seem to work fine for you when doing this?

**Comment by gsavvid** [comment]
@dweremeichik Yes, for me it works fine with MaxVersion=48.*

**Comment by dweremeichik** [comment]
Same for me, it looks like this can be changed in `pencil/build/properties.sh` however I don't know if there are any consequences that we should be aware of. Perhaps @prikhi can way in? I don't see any sort of project tests that can be run.

**Comment by gsavvid** [comment]
I've used it quite extensively the last 1 month or so and I haven't noticed any bugs or weird behavior whatsoever.

**Comment by prikhi** [comment]
Should be fixed. You might want to check out the http://github.com/evolus/pencil repo as well.
