### ISSUE TITLE
Feature Request: Link To external URL

### ISSUE THREAD

**Issue by mr-bobz** [prikhi/pencil#845]
Hi Team,

I am using the beta version (3.0) and is loving this. Great work!

It would be really nice if you could add the option to link to an external URL also, not just other pages in same project. This way a complex design could be split by pages etc instead of having everything in one and hence better manageable.

Regards

**Comment by prikhi** [comment]
For version 3, please open an issue with Evolus' repository: http://github.com/evolus/pencil
