### ISSUE TITLE
Windows Defender found "Trojan: Win32/Varpes.M!cl" during the installation 3.0.0-rc.1 

### ISSUE THREAD

**Issue by asziranyi** [prikhi/pencil#847]
During the installation of `Pencil-Setup-3.0.0-rc.1` the Windows Defender pop-ups with an alert `Trojan: Win32/Varpes.M!cl` found. This is on an up-to-date Windows 10.

**Comment by kn00tcn** [comment]
pencil3 https://github.com/evolus/pencil is a different project than this one (a fork/continuation of the old pencil2)

you should also use more than one scanner such as uploading the installer to https://virustotal.com & also making sure the file hashes of what you downloaded are the same as the official ones

**Comment by prikhi** [comment]
Yup, 3.0 issues should be reported to https://github.com/evolus/pencil
