### ISSUE TITLE
Can't drag'n drop any components

### ISSUE THREAD

**Issue by xinelopunk** [prikhi/pencil#850]
When  I try to drop any of the components into the page, the mouse icon becomes a prohibited symbol and the application don't let me put any components on.

**Comment by phogar** [comment]
Same here. I'm using Firefox 49 with ubuntu xenial 16.04.1 LTS.

**Comment by nikhilw** [comment]
Same here. I am unable to add any component to the page. Is there an alternative to drag-drop cause click does not select the component either. FF 49 on Linux Mint 18. I am basically unable to use the tool at all.

Update: What worked is the 'Next' version mentioned here: http://pencil.evolus.vn/Next.html; developed in this repository: https://github.com/evolus/pencil

**Comment by hellsing71** [comment]
+1 here, like @nikhilw, completely unable to use. Firefox 49.0.1 on latest Win10 x64.

Pencil 3.0.0. RC1 standalone works for me, too.

**Comment by hellodjangodev** [comment]
+1 Same issue with me also. Unable to drag & drop components from sidebar. I use Ubuntu 16.04 LTS.

**Comment by linquize** [comment]
FF49 completely not usable because of drag function

**Comment by waltersf** [comment]
I was facing the same problem. My FF version is 49. A workaround:
- Download source code from github.
- cd <download_dir>/build
- ./build.sh linux
- Edit Outputs/Linux/application.ini and change MaxVersion to a higher number (i.e, 56)
- Run firefox --app Outputs/Linux/application.ini

Good luck!

**Comment by irwan-github** [comment]
Hi waltersf

Thanks for the fix. It worked. For this Pencil, so far so good.

**Comment by prikhi** [comment]
Yeah this is a bug in newer FF versions & neither me nor mozilla have the time to figure out whats going on. I'll keep bumping maxVersion hoping it'll be fixed in the future but either use an older firefox, or use xulrunner/palemoon.
