### ISSUE TITLE
macOS 10.12 not able to move pencil window

### ISSUE THREAD

**Issue by schwedenmut** [prikhi/pencil#851]
Hi guys,
before i start, i wanted to thank y'all for the further development of pencil - keep up the great work! Now my problem, i am running Pencil 2.0.18.20160314 on macOS 10.12 with a LED Cinema Display (Apple) attached over Thunderbolt. Once Pencil is started, i can't drag the Pencil window to another position. Resizing works like a charm - but moving the window is impossible. I have used Pencil prior to macOS 10.12 a lot, and it worked without this problem that days.
What i tried so far:
- disconnect the LED Cinema Display (both Thunderbolt and USB) -> no affect, still not able to more the window
- restart macOS with connected LED Cinema Display -> no affect
- restart macOS without connected LED Cinema Display -> no affect
- restart macOS with connected HDMI Monitor -> no affect
- remove Pencil with app cleaner and reinstall from GitHub v2.0.18 with connected LED Cinema Display -> still no luck.

Actually, installing the "official" 3.0.0 RC1 the moving of the windows does work (yeah, i know thats another software sort of).

**Comment by fengyunhe** [comment]
Move to the top of the edge, when the mouse pointer to modify the height of the icon, press the mouse to move

**Comment by schwedenmut** [comment]
Thanks, even if something is broken, this works (also tested in v 2.0.21.20161120)
