### ISSUE TITLE
Cannot add any widgets on sketch

### ISSUE THREAD

**Issue by cdarken** [prikhi/pencil#853]
I cannot add any items from the collections to my sketch. I'm on Ubuntu 14.04, same thing happens with the standalone version and with the xpi version.

**Comment by wildtype** [comment]
Got the same issue on xubuntu 16.04.1.  I experienced the same problem in the past some years/months ago when using kubuntu.

**Comment by prikhi** [comment]
See #802 
For ubuntu standalone, you can try installing xulrunner
Let me know if you are experiencing a different issue & I'll re-open
