### ISSUE TITLE
"Download for Ubuntu" button on home page leads to a 404 page

### ISSUE THREAD

**Issue by geoffreyvanwyk** [prikhi/pencil#855]
When I click the "Download for Ubuntu" button on the home page, I get a 404 page.

> HTTP Status 404 - /dl/evoluspencil_2.0.5_all.deb
>
> type Status report
>
> message /dl/evoluspencil_2.0.5_all.deb
>
> description The requested resource is not available.
> Apache Tomcat/7.0.37

**Comment by prikhi** [comment]
That is Evolus' home page, not this projects. Our downloads are on this github projects "Releases" page. Alternatively, checkout the Pencil v3 project: http://github.com/evolus/pencil
