### ISSUE TITLE
Install new HTML template

### ISSUE THREAD

**Issue by ianchanning** [prikhi/pencil#861]
I'm using Pencil 3.0.0-rc2 on Windows 10.

If I try to install HTML Templates downloaded from the [Pencil v2 Google Code Downloads page](https://code.google.com/archive/p/evoluspencil/downloads?page=4) then nothing happens.

1. Tools > Manage Export Template...
1. Click on Install new template...
1. Select GUIPrototypingTemplate.zip ([download](https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/evoluspencil/GUIPrototypingTemplate.zip))

Nothing happens. No error message and no new template becomes available to use

**Comment by mbraz** [comment]
I have the same error... nothing happens...

**Comment by Thisn2s** [comment]
If both of you are using Windows 10, I was able to work around this by accessing:
C:\Users\[WindowsUser]\.pencil\exportTemplates\HTML
and unzipping the templates there under their own subfolders
(e.g. C:\Users\Snuffleupagus\.pencil\exportTemplates\HTML\GUIPrototypingTemplate\ [all files should end up here] )

hth

**Comment by prikhi** [comment]
Wrong repo, see http://github.com/evolus/pencil for v3.
