### ISSUE TITLE
Missing collections

### ISSUE THREAD

**Issue by erlendaakre** [prikhi/pencil#862]
There appear to be two collections with dead links in the repo.

### Reproducing ###

1. Install Pencil 3.0.1
2. Click _Manage Collections_
3. Click _Install from Repository..._
4. Click the install button for the collection

The above steps fail (gives the `Failed to find collection at <url>` error message) for the following collections:
- Ext JS Neptune
- Dojo Widgets

**Comment by prikhi** [comment]
Wrong repo, see http://github.com/evolus/pencil for v3.
